project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Swimming in the Charles River: Assessing Biological Swim Safety in Boston's Urban Waterway"
  author:
    - Jared Donohue (jjd2203)
  repo-url: https://github.com/jdonohue44/SwimTheCharlesRiver
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cerulean
    code-fold: true


