project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Swim the Charles River: Analyzing Safe-for-Swim Days in Boston's Charles River"
  author:
    - Jared Donohue (jjd2203)
  repo-url: https://github.com/jdonohue44/SwimTheCharlesRiver
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cerulean
    code-fold: true


