# Data

## Data Sources

- [Water Quality Buoy placed in the Lower Charles River (2015-2024)](https://www.epa.gov/charlesriver/live-water-quality-data-lower-charles-river): Every 15 minutes, this self-contained solar powered buoy takes measurements for temperature, dissolved oxygen, pH, specific conductance, turbidity, chlorophyll, and phycocyanin. The sensors on the buoy are located 1 meter below the water's surface. The data are transmitted in real-time using telemetry for remote access. The data from this buoy is used to assess water quality conditions and to help track cyanobacteria (blue-green algae) blooms.
- [Visual Crossing Historical Weather Data API (2024)](https://www.visualcrossing.com/weather/weather-data-services): Visual Crossing is a provider of weather data and enterprise analysis tools to data scientists, business analysts, professionals, and academics. Founded in 2003, this weather data API leads the industry by providing the lowest-cost access to all types of historical weather data, weather forecasts, climate summaries, and historical weather forecasts.

## Missing Data Analysis

- Covid years are missing water buoy data (2020-2021).
- In order to stay within free-tier usage, only historical weather data from the following time ranges were downloaded from Visual Crossing: 
  - 2024 (daily)
  - August, 2024 (hourly)


